### ISSUE TITLE
Just Doesn't Seem to Be Working

### ISSUE THREAD

**Issue by JonahElbaz** [manicakes/react-native-icloudstore#18]
The concept of the library is exactly what i'm looking for.

I've enabled iCloud and key-value storage through XCode but  can't help but feel like i'm still missing a piece. Tried also turning on iCloud Documents and CloudKit and still when I try to setItem the data doesn't get set.

```
   const key = "test"
   const content = "...some pretty big string...."
    await iCloudStorage.setItem(key, content)

    const d = await iCloudStorage.getItem(key)

    console.log(d)
```
`d` always seems to be undefined. Was hoping someone may know what's going on.
If i figure it out, i'll resolve and add the solution.

Thanks in advance

**Comment by waynedunkley** [comment]
@JonahElbaz I see that you closed this as complete. Did you find the solution to your problem? I'm curious as I'm looking to implement this myself. Thanks

**Comment by JonahElbaz** [comment]
Hey, yeah it turns out i had all the permissions enabled for debug signing keys but not for prod signing keys. Huge oversight on my part. The library still works as expected

**Comment by ceblay** [comment]
@JonahElbaz I seem to have the same issue but not sure I understand your fix. How do I enable all the permissions? Is it on my Apple developer account? I assume the signing keys being spoken about are app signing keys? Thanks!

**Comment by JonahElbaz** [comment]
Hmm, in xcode do you have all the permissions enabled for both release and dev profiles?

**Comment by ceblay** [comment]
I think I see what you mean. My setup is a bit different: developing on Linux but building with Expo. Most likely, once I set up the right permissions at the level of the Apple developer account, it should be fine. Will report here after that's tested. Thank you.
